changelog:
  categories:
    - title: "用户可见变化"
      labels:
        - "feature"
        - "enhancement"
        - "bug"
    - title: "开发与文档"
      labels:
        - "documentation"
        - "chore"
        - "dependencies"
    - title: "其他"
      labels:
        - "*"
